name: django-react-starter-build

services:
  init:
    image: alpine:latest
    volumes:
      - shared:/shared
    command:
      - sh
      - -c
      - |
          rm -f /shared/node-build-done
          touch /shared/build-started
          echo "Build synchronization initialized."
  node:
    image: ${NODE_IMAGE:-node:24-bookworm-slim}
    volumes:
      - ../client:/app
      - shared:/shared
    working_dir: /app
    depends_on:
      init:
        condition: service_completed_successfully
    command:
      - sh 
      - -c
      - |
          echo "Starting Node build..."

          npm ci --no-audit --no-fund &&
          npm run build &&
          touch /shared/node-build-done

          echo "Node build finished."
  python:
    image: ${PYTHON_IMAGE:-python:3.14-slim}
    volumes:
      - ..:/app
      - shared:/shared
    working_dir: /app
    environment:
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:-}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-}
      DJANGO_SETTINGS_MODULE: config.settings.production
      PATH: "/opt/venv/bin:$PATH"
    depends_on:
      init:
        condition: service_completed_successfully
    command: 
      - sh
      - -c
      - |
          DEBIAN_FRONTEND=noninteractive apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends zip
          rm -rf /var/lib/apt/lists/*

          python -m venv /opt/venv
          . /opt/venv/bin/activate

          python -m pip install --upgrade pip
          python -m pip install -r ./requirements.txt
          python manage.py collectstatic --clear --noinput --settings=config.settings.production

          echo "Waiting for Node build to complete..."

          while [ ! -f "/shared/node-build-done" ]; do
            sleep 1
          done

          echo "Node build complete, zipping"

          rm --force web.zip
          zip -r web.zip . \
            -x ".git/*" \
            -x "client/*.json" \
            -x "client/*.js" \
            -x "client/*.html" \
            -x "client/dist/*" \
            -x "client/src/*" \
            -x "client/node_modules/*" \
            -x "*/__pycache__/*" \
            -x "docker/*" \
            -x ".dockerignore" \
            -x ".editorconfig" \
            -x ".gitignore" \
            -x ".nvmrc" \
            -x "requirements.txt" \
            -x "README.md"
volumes:
  shared:
